### ISSUE TITLE
This package does not do what it says

### ISSUE THREAD

**Issue by lucacasonato** [inspect-js/has-proto#2]
In an environment where I `delete Object.prototype.__proto__`, this package returns `true`. It should return `false`. This is because the package description says (emphasis added):

> Does this environment have the ability to **get** or **set** the [[Prototype]] of an object with `__proto__`?

However the package only tests that the environment has the ability to **declare** the [[Prototype]] of an object with `__proto__`. It does not test that **getting** or **setting** through `__proto__` works.

The behaviour the package is testing has also bene uncontroversial for many years and is part of the main 262 spec. Only the getter behaviour is controversial - it is part of annex B and is thus not implemented everywhere (Deno does not implement this feature by default and has a flag to turn it on, while Node has it enabled by default with a flag to disable).

**Comment by ljharb** [comment]
Indeed, the description isn’t accurate.

(it’s worth noting that any web-compatible runtime would be required to implement it, and deno claims to be one)

**Comment by ljharb** [comment]
Ah, that's just the repo description - the package description (the source of truth) is ```Does this environment have the ability to set the [[Prototype]] of an object on creation with `__proto__`?``` which is precisely correct.

Repo description updated.
